public with sharing class CCAviTestUtilSettings {
    /** Constants - Do not change **/
    public static final String PRICE_METHOD_BEST = 'Best Price';
    public static final String PRICE_METHOD_SEQUENCE = 'Sequence Order';

    /** Update these values for the default settings for the Salesforce org **/
    public static final String DEFAULT_COMMUNITY_PROFILE = 'B2B Storefront Registered Login Users acams';
    public static final String DEFAULT_GUEST_USER_PROFILE = 'B2B Storefront Registered Login Users acams';
    public static final String DEFAULT_COMMUNITY_NAME = 'acams';
    public static final String DEFAULT_STOREFRONT = 'acams';
    public static final String DEFAULT_PRICE_METHOD = PRICE_METHOD_BEST;

}