@isTest
public class wsPearsonvueComPingSchemaTest {

    @isTest
    static void pingRequestType_test() {
        wsPearsonvueComPingSchema.pingRequestType prt = new wsPearsonvueComPingSchema.pingRequestType();
    }

    @isTest
    static void pingResponseType_test() {
        wsPearsonvueComPingSchema.pingResponseType prst = new wsPearsonvueComPingSchema.pingResponseType();
    }

    @isTest
    static void resultType_test() {
        wsPearsonvueComPingSchema.resultType rt = new wsPearsonvueComPingSchema.resultType();
    }

}