@isTest
public class wsPearsonvueComRtiEadSchemaTest {

    @isTest
    static void eadRequestType_test() {
        wsPearsonvueComRtiEadSchema.eadRequestType ert = new wsPearsonvueComRtiEadSchema.eadRequestType();
    }

    @isTest
    static void customFieldsType_test() {
        wsPearsonvueComRtiEadSchema.customFieldsType cft = new wsPearsonvueComRtiEadSchema.customFieldsType();
    }

    @isTest
    static void moduleType_test() {
        wsPearsonvueComRtiEadSchema.moduleType mdt = new wsPearsonvueComRtiEadSchema.moduleType();
    }

    @isTest
    static void modulesType_test() {
        wsPearsonvueComRtiEadSchema.modulesType mdst = new wsPearsonvueComRtiEadSchema.modulesType();
    }

    @isTest
    static void clientAccommodationType_test() {
        wsPearsonvueComRtiEadSchema.clientAccommodationType cat = new wsPearsonvueComRtiEadSchema.clientAccommodationType();
    }

    @isTest
    static void clientAccommodationsType_test() {
        wsPearsonvueComRtiEadSchema.clientAccommodationsType cats = new wsPearsonvueComRtiEadSchema.clientAccommodationsType();
    }

    @isTest
    static void fieldType_test() {
        wsPearsonvueComRtiEadSchema.fieldType ft = new wsPearsonvueComRtiEadSchema.fieldType();
    }

    @isTest
    static void eadResponseType_test() {
        wsPearsonvueComRtiEadSchema.eadResponseType erst = new wsPearsonvueComRtiEadSchema.eadResponseType();
    }
    
}